### PR TITLE
Create ticket

### PR DESCRIPTION
**Pull request by zacharyehren**
Hey Ben, I was able complete setting up the `create` method which creates a brand new ticket. What I'm having trouble with now is creating a comment (response) within an already existing ticket. Here's how I would imagine it happening:

```ruby
ZEN_CLIENT.tickets.find(id: 4).comments.create(:comment => {:value => "Zach is sending a comment"}, :requester => {:name => "Zach"})
```
So, 
1. The request finds ticket with the id of 4
2. Then pulls in the comments object and calls the create method
3. Then passes in the info

However, when approaching it this way, I get the following error:

`NoMethodError: undefined method "create" for ZendeskAPI::Ticket::Comment`

I've also tried it this way:

```ruby
ZEN_CLIENT.tickets.find(id: 4).create(:comment => {:value => "Zach is sending a comment"}, :requester => {:name => "Zach"} )
```
Which removes the comment object. But this returns `nil`. 

I've been looking through the Client docs but not having any luck with details on how to create a comment. Here's the ZD API doc which details how to create comments, but not within the Ruby Client: https://developer.zendesk.com/rest_api/docs/core/ticket_comments

### CODE REVIEW

**Comment by zacharyehren** [comment]
And just in case you need it, here's the Ruby Client doc: https://github.com/zendesk/zendesk_api_client_rb/

**Comment by bmneely** [comment]
I think you need to do something like:

```ruby
ticket.comment = {body: "A public comment with layman's term of the problem."}
ticket.save
```

**Comment by zacharyehren** [comment]
This is another example of one step forward, two steps back... I figured out how to create a new comment within an existing ticket which can be seen below:

```ruby
def create_comment
    ticket = ZEN_CLIENT.tickets.find(id: params[:id])
    ticket.update(comment: {:body => body, :via => { :source => { :from => { :name => submitter }}}, :requester => { :name => submitter }})
    ticket.save
  end
```

This creates the comment body, but the problem I noticed is that the `submitter` name wasn't going through. When I look in Zendesk, the submitter's name is the admin of the account, which isn't useful if an end-user is making the comment. So I did some digging in their support docs and found that you can't pass through this info on a new comment for some reason. It has to be done through their ID. Details can be found here: https://support.zendesk.com/hc/en-us/community/posts/207597658-Adding-comments-to-existing-ticket-as-end-user

According to that doc "It's as simple as setting the author_id to the id of the end-user." So I updated the method as follows:

```ruby
def create_comment
    user = ZEN_CLIENT.users.search(:query => user_email)
    ticket = ZEN_CLIENT.tickets.find(id: params[:id])
    ticket.update(comment: {:body => "body", author_id => user.id })
    ticket.save
  end
```
I verified in the docs that the search for a user by email is correct, but I'm not pulling the user's ID correctly. When I test the method, I'm receiving the following error:

```
{"error"=>{"title"=>"Invalid attribute", "message"=>"You passed an invalid value for the author_id attribute. Invalid parameter: author_id must be an integer"}}
```
So the id isn't being pulled in correctly. But I also may be misinterpreting how to go about doing this in general.

**Comment by bmneely** [comment]
I'm guessing `user.id` returns a string, so you'll need to cast it to an int with `.to_i`

**Pull request closed without merging**
